In [1]:
import numpy as np
test_X = np.load('X_test.npy')
test_Y = np.load('y_test.npy')

In [6]:
test_X[171]

array([[ 0.65287981,  0.64132335,  0.62761705, ...,  0.61418011,
         0.60181725,  0.59832313],
       [-0.68240952, -0.68209588, -0.68052927, ..., -0.71310953,
        -0.71060281, -0.7090362 ],
       [ 0.69386093,  0.69386093,  0.69386093, ...,  0.69386093,
         0.69386093,  0.69386093],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.09582784, -0.09582784, -0.09582784, ..., -0.09582784,
        -0.09582784, -0.09582784],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [7]:
test_Y[172]

array([1], dtype=uint8)

In [2]:
id = np.where(test_Y == 1)
id

(array([295, 296, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327,
        328, 329, 330, 331, 335, 336, 337, 338, 339, 340, 341, 342, 343,
        344, 345, 346, 347, 359, 360, 361, 362, 363, 364, 365, 376, 377,
        378, 379, 380, 381, 382, 383, 384, 385, 566, 567, 568, 569, 570,
        571, 572, 573, 574, 575, 576, 577], dtype=int64),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64))